CREATE DATABASE IF NOT EXISTS SALES_ANALYTICS;
USE DATABASE SALES_ANALYTICS;

CREATE SCHEMA IF NOT EXISTS BRONZE;
CREATE SCHEMA IF NOT EXISTS SILVER;
CREATE SCHEMA IF NOT EXISTS GOLD;
CREATE SCHEMA IF NOT EXISTS REPORTING;

CREATE OR REPLACE STORAGE INTEGRATION SALES_ANALYTICS_S3_INT
TYPE = EXTERNAL_STAGE
STORAGE_PROVIDER = 'S3'
ENABLED = TRUE
STORAGE_AWS_ROLE_ARN = '<AWS_ROLE_ARN>'
STORAGE_ALLOWED_LOCATIONS = (
    's3://sales-analytics-aditya-task-2/raw/'
);

USE SCHEMA BRONZE;

CREATE OR REPLACE FILE FORMAT RAW_JSON_FORMAT
TYPE = 'JSON'
COMPRESSION = 'AUTO'
STRIP_OUTER_ARRAY = FALSE;

CREATE OR REPLACE STAGE S3_RAW_STAGE
URL = 's3://sales-analytics-aditya-task-2/raw/'
STORAGE_INTEGRATION = SALES_ANALYTICS_S3_INT
FILE_FORMAT = RAW_JSON_FORMAT;
