USE DATABASE SALES_ANALYTICS;
USE SCHEMA BRONZE;

CREATE OR REPLACE TABLE LEADS_RAW
(
    RAW_DATA VARIANT,
    INSERT_DATE TIMESTAMP_NTZ
);

CREATE OR REPLACE TABLE LEAD_ACTIVITIES_RAW
(
    RAW_DATA VARIANT,
    INSERT_DATE TIMESTAMP_NTZ
);

CREATE OR REPLACE TABLE CUSTOM_ACTIVITIES_RAW
(
    RAW_DATA VARIANT,
    INSERT_DATE TIMESTAMP_NTZ
);

CREATE OR REPLACE TABLE CLOSE_CRM_USERS_RAW
(
    RAW_DATA VARIANT,
    INSERT_DATE TIMESTAMP_NTZ
);

COPY INTO LEADS_RAW
(
    RAW_DATA,
    INSERT_DATE
)
FROM
(
    SELECT
        $1:raw_data,
        $1:insert_date::TIMESTAMP_NTZ
    FROM @S3_RAW_STAGE/leads/
)
FILE_FORMAT = (
    FORMAT_NAME = 'RAW_JSON_FORMAT'
)
ON_ERROR = 'ABORT_STATEMENT';

COPY INTO LEAD_ACTIVITIES_RAW
(
    RAW_DATA,
    INSERT_DATE
)
FROM
(
    SELECT
        $1:raw_data,
        $1:insert_date::TIMESTAMP_NTZ
    FROM @S3_RAW_STAGE/lead_activities/
)
FILE_FORMAT = (
    FORMAT_NAME = 'RAW_JSON_FORMAT'
)
PATTERN = '.*part-.*[.]json'
ON_ERROR = 'ABORT_STATEMENT';

COPY INTO CUSTOM_ACTIVITIES_RAW
(
    RAW_DATA,
    INSERT_DATE
)
FROM
(
    SELECT
        $1:raw_data,
        $1:insert_date::TIMESTAMP_NTZ
    FROM @S3_RAW_STAGE/custom_activities/
)
FILE_FORMAT = (
    FORMAT_NAME = 'RAW_JSON_FORMAT'
)
PATTERN = '.*part-.*[.]json'
ON_ERROR = 'ABORT_STATEMENT';

COPY INTO CLOSE_CRM_USERS_RAW
(
    RAW_DATA,
    INSERT_DATE
)
FROM
(
    SELECT
        $1:raw_data,
        $1:insert_date::TIMESTAMP_NTZ
    FROM @S3_RAW_STAGE/close_crm_users/
)
FILE_FORMAT = (
    FORMAT_NAME = 'RAW_JSON_FORMAT'
)
PATTERN = '.*part-.*[.]json'
ON_ERROR = 'ABORT_STATEMENT';
