CREATE DATABASE IF NOT EXISTS SALES_ANALYTICS;
CREATE SCHEMA IF NOT EXISTS SALES_ANALYTICS.BRONZE;
CREATE SCHEMA IF NOT EXISTS SALES_ANALYTICS.SILVER;
CREATE SCHEMA IF NOT EXISTS SALES_ANALYTICS.GOLD;
CREATE SCHEMA IF NOT EXISTS SALES_ANALYTICS.REPORTING;
USE DATABASE SALES_ANALYTICS;
CREATE TABLE IF NOT EXISTS BRONZE.RAW_RECORDS (
    SOURCE_TABLE STRING NOT NULL, RUN_ID STRING NOT NULL, RAW_DATA STRING,
    INSERT_DATE_TEXT STRING, EXTRACTED_AT TIMESTAMP_TZ,
    SOURCE_FILE STRING NOT NULL, SOURCE_FILE_ROW NUMBER NOT NULL, LOADED_AT TIMESTAMP_TZ
);
CREATE TABLE IF NOT EXISTS BRONZE.INGESTION_RUNS (
    RUN_ID STRING NOT NULL, STARTED_AT TIMESTAMP_TZ NOT NULL,
    COMPLETED_AT TIMESTAMP_TZ NOT NULL, MANIFEST_URI STRING,
    MANIFEST VARIANT, LOADED_AT TIMESTAMP_TZ
);
CREATE FILE FORMAT IF NOT EXISTS BRONZE.RAW_JSON TYPE=JSON COMPRESSION=AUTO;
