USE DATABASE SALES_ANALYTICS;
CREATE STAGE IF NOT EXISTS BRONZE.S3_RAW_STAGE
  URL='s3://sales-analytics-aditya-task-2/raw/'
  STORAGE_INTEGRATION=SALES_ANALYTICS_S3_INT
  FILE_FORMAT=BRONZE.RAW_JSON;
LIST @BRONZE.S3_RAW_STAGE;
