USE DATABASE SALES_ANALYTICS;
CREATE OR REPLACE VIEW SILVER.LATEST_RUN AS
SELECT * FROM BRONZE.INGESTION_RUNS
QUALIFY ROW_NUMBER() OVER (ORDER BY STARTED_AT DESC, RUN_ID DESC)=1;

CREATE OR REPLACE VIEW SILVER.DECODED_RECORDS AS
WITH P0 AS (
 SELECT R.*, TRY_PARSE_JSON(R.RAW_DATA) AS PAYLOAD
 FROM BRONZE.RAW_RECORDS R JOIN SILVER.LATEST_RUN L ON R.RUN_ID=L.RUN_ID
),
P1 AS (
 SELECT * EXCLUDE PAYLOAD,
   CASE WHEN TYPEOF(PAYLOAD)='VARCHAR' THEN TRY_PARSE_JSON(PAYLOAD::STRING)
        WHEN TYPEOF(PAYLOAD)='OBJECT' AND PAYLOAD:JSON_OBJECT IS NOT NULL
          THEN CASE WHEN TYPEOF(PAYLOAD:JSON_OBJECT)='VARCHAR'
                    THEN TRY_PARSE_JSON(PAYLOAD:JSON_OBJECT::STRING)
                    ELSE PAYLOAD:JSON_OBJECT END
        ELSE PAYLOAD END AS PAYLOAD
 FROM P0
),
P2 AS (
 SELECT * EXCLUDE PAYLOAD,
   CASE WHEN TYPEOF(PAYLOAD)='VARCHAR' THEN TRY_PARSE_JSON(PAYLOAD::STRING)
        WHEN TYPEOF(PAYLOAD)='OBJECT' AND PAYLOAD:JSON_OBJECT IS NOT NULL
          THEN CASE WHEN TYPEOF(PAYLOAD:JSON_OBJECT)='VARCHAR'
                    THEN TRY_PARSE_JSON(PAYLOAD:JSON_OBJECT::STRING)
                    ELSE PAYLOAD:JSON_OBJECT END
        ELSE PAYLOAD END AS PAYLOAD
 FROM P1
),
P3 AS (
 SELECT * EXCLUDE PAYLOAD,
   CASE WHEN TYPEOF(PAYLOAD)='VARCHAR' THEN TRY_PARSE_JSON(PAYLOAD::STRING)
        WHEN TYPEOF(PAYLOAD)='OBJECT' AND PAYLOAD:JSON_OBJECT IS NOT NULL
          THEN CASE WHEN TYPEOF(PAYLOAD:JSON_OBJECT)='VARCHAR'
                    THEN TRY_PARSE_JSON(PAYLOAD:JSON_OBJECT::STRING)
                    ELSE PAYLOAD:JSON_OBJECT END
        ELSE PAYLOAD END AS PAYLOAD
 FROM P2
),
P4 AS (
 SELECT * EXCLUDE PAYLOAD,
   CASE WHEN TYPEOF(PAYLOAD)='VARCHAR' THEN TRY_PARSE_JSON(PAYLOAD::STRING)
        WHEN TYPEOF(PAYLOAD)='OBJECT' AND PAYLOAD:JSON_OBJECT IS NOT NULL
          THEN CASE WHEN TYPEOF(PAYLOAD:JSON_OBJECT)='VARCHAR'
                    THEN TRY_PARSE_JSON(PAYLOAD:JSON_OBJECT::STRING)
                    ELSE PAYLOAD:JSON_OBJECT END
        ELSE PAYLOAD END AS PAYLOAD
 FROM P3
)

SELECT *,
 CASE WHEN RAW_DATA IS NULL THEN 'NULL_RAW_DATA'
      WHEN PAYLOAD IS NULL OR IS_NULL_VALUE(PAYLOAD) THEN 'INVALID_OR_NULL_JSON'
      WHEN TYPEOF(PAYLOAD)='OBJECT' AND PAYLOAD:JSON_OBJECT IS NOT NULL THEN 'WRAPPER_DEPTH_EXCEEDED'
      WHEN TYPEOF(PAYLOAD) NOT IN ('OBJECT','ARRAY') THEN 'UNSUPPORTED_JSON_SCALAR'
      WHEN TYPEOF(PAYLOAD)='OBJECT' AND PAYLOAD:data IS NOT NULL
           AND TYPEOF(PAYLOAD:data)<>'ARRAY' THEN 'UNSUPPORTED_DATA_WRAPPER'
      ELSE 'OK' END AS PARSE_STATUS
FROM P4;

CREATE OR REPLACE VIEW SILVER.RECORD_ISSUES AS
SELECT * FROM SILVER.DECODED_RECORDS WHERE PARSE_STATUS<>'OK';

CREATE OR REPLACE VIEW SILVER.ENTITIES AS
SELECT D.SOURCE_TABLE, D.RUN_ID, D.SOURCE_FILE, D.SOURCE_FILE_ROW,
 F.INDEX AS ARRAY_INDEX, F.VALUE AS ENTITY,
 D.INSERT_DATE_TEXT, D.EXTRACTED_AT,
 CASE WHEN TYPEOF(F.VALUE)='OBJECT' THEN 'OK' ELSE 'NON_OBJECT_ENTITY' END AS ENTITY_STATUS
FROM SILVER.DECODED_RECORDS D,
 LATERAL FLATTEN(INPUT => CASE
   WHEN TYPEOF(D.PAYLOAD)='ARRAY' THEN D.PAYLOAD
   WHEN TYPEOF(D.PAYLOAD:data)='ARRAY' THEN D.PAYLOAD:data
   ELSE ARRAY_CONSTRUCT(D.PAYLOAD) END) F
WHERE D.PARSE_STATUS='OK';
-- Empty arrays intentionally produce zero entities, but remain in DECODED_RECORDS.
-- No entity IDs or business timestamps are inferred before field mapping is reviewed.

CREATE OR REPLACE VIEW SILVER.ENTITY_ISSUES AS
SELECT * FROM SILVER.ENTITIES WHERE ENTITY_STATUS<>'OK';

CREATE OR REPLACE VIEW SILVER.LEADS AS
SELECT * FROM SILVER.ENTITIES WHERE SOURCE_TABLE='raw.leads_raw' AND ENTITY_STATUS='OK';

CREATE OR REPLACE VIEW SILVER.LEAD_ACTIVITIES AS
SELECT * FROM SILVER.ENTITIES WHERE SOURCE_TABLE='raw.lead_activites_raw' AND ENTITY_STATUS='OK';

CREATE OR REPLACE VIEW SILVER.CLOSE_CRM_USERS AS
SELECT * FROM SILVER.ENTITIES WHERE SOURCE_TABLE='raw.close_crm_users_raw' AND ENTITY_STATUS='OK';

CREATE OR REPLACE VIEW SILVER.CUSTOM_ACTIVITIES AS
SELECT * FROM SILVER.ENTITIES WHERE SOURCE_TABLE='raw.custom_activites_raw' AND ENTITY_STATUS='OK';
