USE DATABASE SALES_ANALYTICS;
-- Operational metrics only. Source rows are envelopes; entities may be array items.
CREATE OR REPLACE VIEW GOLD.SOURCE_HEALTH AS
WITH EXPECTED AS (
 SELECT L.RUN_ID, L.STARTED_AT, L.COMPLETED_AT, L.LOADED_AT,
   F.VALUE:source_table::STRING AS SOURCE_TABLE,
   F.VALUE:row_count::NUMBER AS EXPECTED_SOURCE_ROWS
 FROM SILVER.LATEST_RUN L, LATERAL FLATTEN(INPUT=>L.MANIFEST:tables) F
), SOURCE_COUNTS AS (
 SELECT SOURCE_TABLE, COUNT(*) AS SOURCE_ROWS,
   COUNT_IF(PARSE_STATUS<>'OK') AS INVALID_SOURCE_ROWS
 FROM SILVER.DECODED_RECORDS GROUP BY SOURCE_TABLE
), ITEMS AS (
 SELECT SOURCE_TABLE, COUNT_IF(ENTITY_STATUS='OK') AS ENTITY_COUNT,
   COUNT_IF(ENTITY_STATUS<>'OK') AS INVALID_ENTITIES
 FROM SILVER.ENTITIES GROUP BY SOURCE_TABLE
)
SELECT E.*, COALESCE(R.SOURCE_ROWS,0) AS SOURCE_ROWS,
 COALESCE(R.INVALID_SOURCE_ROWS,0) AS INVALID_SOURCE_ROWS,
 COALESCE(I.ENTITY_COUNT,0) AS ENTITY_COUNT,
 COALESCE(I.INVALID_ENTITIES,0) AS INVALID_ENTITIES,
 DATEDIFF('minute', E.STARTED_AT, CURRENT_TIMESTAMP()) AS SNAPSHOT_AGE_MINUTES,
 COALESCE(R.SOURCE_ROWS,0)=E.EXPECTED_SOURCE_ROWS AS COUNTS_MATCH
FROM EXPECTED E LEFT JOIN SOURCE_COUNTS R ON E.SOURCE_TABLE=R.SOURCE_TABLE
LEFT JOIN ITEMS I ON E.SOURCE_TABLE=I.SOURCE_TABLE;

CREATE OR REPLACE VIEW REPORTING.PIPELINE_STATUS AS SELECT * FROM GOLD.SOURCE_HEALTH;
CREATE OR REPLACE VIEW REPORTING.LOAD_HISTORY AS
SELECT RUN_ID, STARTED_AT, COMPLETED_AT, LOADED_AT, MANIFEST_URI
FROM BRONZE.INGESTION_RUNS;
