USE DATABASE SALES_ANALYTICS;
SELECT * FROM REPORTING.PIPELINE_STATUS ORDER BY SOURCE_TABLE;
-- These issue queries should return no rows for fully supported data:
SELECT RUN_ID, COUNT(*) FROM BRONZE.INGESTION_RUNS GROUP BY 1 HAVING COUNT(*)<>1;
SELECT RUN_ID, SOURCE_FILE, SOURCE_FILE_ROW, COUNT(*) FROM BRONZE.RAW_RECORDS
GROUP BY 1,2,3 HAVING COUNT(*)<>1;
SELECT * FROM REPORTING.PIPELINE_STATUS WHERE NOT COUNTS_MATCH;
SELECT SOURCE_TABLE, PARSE_STATUS, COUNT(*) FROM SILVER.RECORD_ISSUES GROUP BY 1,2;
SELECT SOURCE_TABLE, ENTITY_STATUS, COUNT(*) FROM SILVER.ENTITY_ISSUES GROUP BY 1,2;
-- Inspect samples privately before defining business mappings:
SELECT SOURCE_TABLE, ENTITY FROM SILVER.ENTITIES LIMIT 20;
